exParcial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('wikiApp.urls'))
]

wikiApp/urls.py
from django.urls import path
from . import views

app_name='wikiApp'

urlpatterns = [
    path('',views.vistaPrincipal,name='vistaPrincipal'),
    path('nuevoArticulo',views.nuevoArticulo,name='nuevoArticulo'),
    path('nuevoTema',views.nuevoTema,name='nuevoTema'),
    path('articulos',views.articulos,name='articulos'),
    path('temas',views.temas,name='temas'),
    path('verTema/<str:idTema>',views.verTema,name='verTema')
]   

wikiApp/models.py
from django.db import models

# Create your models here.

class tema(models.Model):
    nombreTema = models.CharField(max_length=128, null=True, blank=True)
    descripcionTema = models.CharField(max_length=512, null=True, blank=True)

class articulo(models.Model):
    tituloArticulo = models.CharField(max_length=128, null=True, blank=True)
    descripcionArticulo = models.CharField(max_length=1024, null=True, blank=True)
    fechaArticulo = models.CharField(max_length=8, null=True, blank=True)
    temaArticulo = models.CharField(max_length=128, null=True, blank=True)
    temaR = models.ForeignKey(tema, null=True, blank=True, on_delete=models.SET_NULL)

wikiApp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import articulo,tema

# Create your views here.
def vistaPrincipal(request):
    return render(request,'vistaPrincipal.html',{
        'temasSistema':tema.objects.all()
    })

def nuevoArticulo(request):
    if request.method == 'POST':
        tituloArticulo = request.POST.get('tituloArticulo')
        descripcionArticulo = request.POST.get('descripcionArticulo')
        fechaArticulo = request.POST.get('fechaArticulo')
        temaSeleccionado = request.POST.get('temaSeleccionado')
        temaObj = tema.objects.get(id=temaSeleccionado)
        articulo.objects.create(
            tituloArticulo = tituloArticulo,
            descripcionArticulo = descripcionArticulo,
            fechaArticulo = fechaArticulo,
            temaR=temaObj            
        )  
        return HttpResponseRedirect(reverse('wikiApp:articulos'))    
    return render(request,'nuevoArticulo.html',{
        'temasSistema':tema.objects.all()
    })    

def nuevoTema(request):
    if request.method == 'POST':
        nombreTema = request.POST.get('nombreTema')
        descripcionTema = request.POST.get('descripcionTema')
        tema.objects.create(
            nombreTema = nombreTema,
            descripcionTema = descripcionTema          
        ) 
        return HttpResponseRedirect(reverse('wikiApp:temas'))
    return render(request,'nuevoTema.html',{
        'temasSistema':tema.objects.all()
    })

def articulos(request):
    articulosTotales = articulo.objects.all()
    return render(request,'articulos.html',{
        'articulosTotales':articulosTotales,
        'temasSistema':tema.objects.all()       
    })

def temas(request):
    temasTotales = tema.objects.all()
    return render(request,'temas.html',{
        'temasTotales':temasTotales,
        'temasSistema':tema.objects.all()       
    })

def verTema(request,idTema):
    temaInfo = tema.objects.get(id=idTema)
    listaArticulos = temaInfo.articulo_set.all()
    return render(request,'verTema.html',{
        'objTema':temaInfo,
        'temasSistema':tema.objects.all(),
        'listaArticulos': listaArticulos
    })

wikiApp/templates/articulos.html
{% extends "layout.html" %}

{% block titulo %}
    Artículos
{% endblock %}

{% block contenido %}
    <h2>Lista de Artículos</h2>
    <ol>
        {% for articuloInfo in articulosTotales %}
        <br>
        <li>
            <ul>
                <li>Título: {{articuloInfo.tituloArticulo}}</li>
                <li>Descripción: {{articuloInfo.descripcionArticulo}}</li>
                <li>Fecha: {{articuloInfo.fechaArticulo}}</li>
                <li>Tema: {{articuloInfo.temaR.nombreTema}}</li>
            </ul>
        </li>
        {% endfor %}        
    </ol>
{% endblock %}

wikiApp/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block titulo %}{% endblock %}</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body>
        <div class="row">
            <div class="col-3">
                <h2>Wikipedia</h2>
                <div>
                    <a href="{% url 'wikiApp:vistaPrincipal' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wikiApp:nuevoArticulo' %}">Crear Nuevo Artículo</a>
                </div>
                <div>
                    <a href="{% url 'wikiApp:nuevoTema' %}">Crear Nuevo Tema</a>
                </div>
                <div>
                    <a href="{% url 'wikiApp:articulos' %}">Artículos</a>
                </div>
                <div>
                    <a href="{% url 'wikiApp:temas' %}">Temas</a>
                </div>
                <br>
                {% for temaInfo in temasSistema %}                
                <div>
                    <a href="{% url 'wikiApp:verTema' temaInfo.id %}">Ver {{ temaInfo.nombreTema }}</a>
                </div>
                {% endfor %}
            </div>    
            <div class="col-9">
                {% block contenido %}

                {% endblock %}
            </div>
        </div>  
    </body>
</html>

wikiApp/templates/nuevoArticulo.html
{% extends "layout.html" %}

{% block titulo %}
    Nuevo Artículo
{% endblock %}

{% block contenido %}
    <h2>Crear nuevo artículo</h2>
    <form class="row" method="post" action="{% url 'wikiApp:nuevoArticulo' %}"> 
        {% csrf_token %}
        <div>
            <label>Ingrese título del artículo</label>
            <input type="text" name="tituloArticulo">
        </div>
        <div>
            <label>Ingrese descripción del artículo</label>
            <input type="text" name="descripcionArticulo">
        </div>
        <div>
            <label>Ingrese fecha de registro del artículo</label>
            <input type="text" name="fechaArticulo">
        </div>      
        <div>
            <label>Seleccionar tema</label>
            <select name="temaSeleccionado">
                {% for temaInfo in temasSistema %}
                <option value="{{ temaInfo.id }}">{{ temaInfo.nombreTema }}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <input type="submit" value="Registrar">
        </div>
    </form>
{% endblock %}

wikiApp/templates/nuevoTema.html
{% extends "layout.html" %}

{% block titulo %}
    Nuevo Tema
{% endblock %}

{% block contenido %}
    <h2>Crear nuevo tema</h2>
    <form class="row" method="post" action="{% url 'wikiApp:nuevoTema' %}"> 
        {% csrf_token %}
        <div>
            <label>Ingrese nombre del tema</label>
            <input type="text" name="nombreTema">
        </div>
        <div>
            <label>Ingrese descripción del tema</label>
            <input type="text" name="descripcionTema">
        </div>        
        <div>
            <input type="submit" value="Registrar">
        </div>
    </form>
{% endblock %}

wikiApp/templates/temas.html
{% extends "layout.html" %}

{% block titulo %}
    Temas
{% endblock %}

{% block contenido %}
    <h2>Lista de Temas</h2>
    <ol>
        {% for temaInfo in temasTotales %}
        <br>
        <li>
            <ul>
                <li>Tema: {{temaInfo.nombreTema}}</li>
                <li>Descripción: {{temaInfo.descripcionTema}}</li>                
            </ul>
        </li>
        {% endfor %}        
    </ol>
{% endblock %}

wikiApp/templates/verTema.html
{% extends "layout.html" %}

{% block titulo %}
    Tema: {{ objTema.nombreTema }}
{% endblock %}

{% block contenido %}
    <h2>TEMA: {{ objTema.nombreTema }}</h2>
    <div>
        <h4>LISTA DE ARTÍCULOS</h4>
        {% for articuloInfo in listaArticulos %}
        <div>
            <ul>
                <li>{{ articuloInfo.tituloArticulo }}</li>
                <li>{{ articuloInfo.fechaArticulo }}</li>
            </ul>
        </div>
        <br>
        {% endfor %}
    </div> 
{% endblock %}

wikiApp/templates/vistaPrincipal.html
{% extends "layout.html" %}

{% block titulo %}
    Wikipedia
{% endblock %}

{% block contenido %}
    Página Principal
{% endblock %}